# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  nobleguppies:
    image: nobleguppies
    build:
      context: .
      dockerfile: noble-guppies-demo/Dockerfile
    ports:
      - 5000:80